<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCc7Fzb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCc7Fzb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCc7Fzb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCc7Fzb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWCc7Fzb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WCc7Fzb',
    'container.build_id' => '77875350',
    'container.build_time' => 1565625495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCc7Fzb');
