<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM78809I\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM78809I/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM78809I.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM78809I\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM78809I\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M78809I',
    'container.build_id' => '5624c6aa',
    'container.build_time' => 1565622377,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM78809I');
